// ─── Profession Data — Materials, Recipes, World Loot Tables ──────────
// Extracted from ProfessionSystem.ts for modularity.

import type { ProfessionType, CraftingMaterial, CraftingRecipe } from './ProfessionSystem';

// ─── Materials ───────────────────────────────────────────────────

export const MATERIALS: CraftingMaterial[] = [
  // Mining
  { id: 'minerai_fer', name: 'Minerai de Fer', profession: 'mining', rarity: 'common', icon: 'ore_grey' },
  { id: 'minerai_acier', name: 'Minerai d\'Acier', profession: 'mining', rarity: 'uncommon', icon: 'ore_silver' },
  { id: 'minerai_pewter', name: 'Minerai de Pewter', profession: 'mining', rarity: 'uncommon', icon: 'ore_blue' },
  { id: 'minerai_atium', name: 'Minerai d\'Atium', profession: 'mining', rarity: 'epic', icon: 'ore_gold' },
  { id: 'gemme_lumiere', name: 'Gemme de Lumiere', profession: 'mining', rarity: 'rare', icon: 'gem_cyan' },
  // Herbalism
  { id: 'herbe_soins', name: 'Herbe de Soins', profession: 'herbalism', rarity: 'common', icon: 'herb_green' },
  { id: 'fleur_nalthis', name: 'Fleur de Nalthis', profession: 'herbalism', rarity: 'uncommon', icon: 'herb_purple' },
  { id: 'racine_orage', name: 'Racine d\'Orage', profession: 'herbalism', rarity: 'uncommon', icon: 'herb_blue' },
  { id: 'mousse_shadesmar', name: 'Mousse de Shadesmar', profession: 'herbalism', rarity: 'rare', icon: 'herb_dark' },
  { id: 'lotus_investiture', name: 'Lotus d\'Investiture', profession: 'herbalism', rarity: 'epic', icon: 'herb_gold' },
  // Woodcutting
  { id: 'bois_commun', name: 'Bois Commun', profession: 'woodcutting', rarity: 'common', icon: 'wood_brown' },
  { id: 'bois_roshar', name: 'Bois de Coquebois', profession: 'woodcutting', rarity: 'uncommon', icon: 'wood_red' },
  { id: 'bois_petrifie', name: 'Bois Petrifie', profession: 'woodcutting', rarity: 'rare', icon: 'wood_grey' },
  // Skinning
  { id: 'cuir_brut', name: 'Cuir Brut', profession: 'skinning', rarity: 'common', icon: 'hide_tan' },
  { id: 'ecailles_crustace', name: 'Ecailles de Crustace', profession: 'skinning', rarity: 'uncommon', icon: 'hide_blue' },
  { id: 'peau_larkin', name: 'Peau de Larkin', profession: 'skinning', rarity: 'rare', icon: 'hide_purple' },
  { id: 'carapace_epine', name: 'Carapace d\'Epine', profession: 'skinning', rarity: 'epic', icon: 'hide_black' },
  // Enchanting
  { id: 'poudre_arcane', name: 'Poudre Arcane', profession: 'enchanting', rarity: 'common', icon: 'dust_blue' },
  { id: 'cristal_investiture', name: 'Cristal d\'Investiture', profession: 'enchanting', rarity: 'rare', icon: 'crystal_cyan' },
  { id: 'sable_blanc', name: 'Sable Blanc', profession: 'enchanting', rarity: 'uncommon', icon: 'sand_white' },
];

// ─── World → Gathering Loot Tables ──────────────────────────────

export const WORLD_LOOT: Record<string, Partial<Record<ProfessionType, string[]>>> = {
  scadrial: {
    mining: ['minerai_fer', 'minerai_acier', 'minerai_pewter', 'minerai_atium'],
    herbalism: ['herbe_soins'],
    skinning: ['cuir_brut'],
    woodcutting: ['bois_commun'],
    enchanting: ['poudre_arcane'],
  },
  roshar: {
    mining: ['minerai_fer', 'gemme_lumiere'],
    herbalism: ['herbe_soins', 'racine_orage'],
    skinning: ['ecailles_crustace', 'carapace_epine'],
    woodcutting: ['bois_roshar'],
    enchanting: ['poudre_arcane', 'cristal_investiture'],
  },
  taldain: {
    mining: ['minerai_fer'],
    herbalism: ['herbe_soins'],
    skinning: ['cuir_brut'],
    woodcutting: ['bois_commun'],
    enchanting: ['sable_blanc', 'poudre_arcane'],
  },
  nalthis: {
    mining: ['minerai_fer'],
    herbalism: ['herbe_soins', 'fleur_nalthis', 'lotus_investiture'],
    skinning: ['cuir_brut'],
    woodcutting: ['bois_commun'],
    enchanting: ['poudre_arcane'],
  },
  sel: {
    mining: ['minerai_fer', 'minerai_acier'],
    herbalism: ['herbe_soins'],
    skinning: ['cuir_brut'],
    woodcutting: ['bois_commun', 'bois_petrifie'],
    enchanting: ['poudre_arcane', 'cristal_investiture'],
  },
  komashi: {
    mining: ['minerai_fer'],
    herbalism: ['herbe_soins', 'mousse_shadesmar'],
    skinning: ['cuir_brut', 'peau_larkin'],
    woodcutting: ['bois_commun'],
    enchanting: ['poudre_arcane'],
  },
  shadesmar: {
    mining: ['gemme_lumiere', 'minerai_atium'],
    herbalism: ['mousse_shadesmar', 'lotus_investiture'],
    skinning: ['peau_larkin', 'carapace_epine'],
    woodcutting: ['bois_petrifie'],
    enchanting: ['cristal_investiture', 'sable_blanc'],
  },
};

// ─── Recipes ─────────────────────────────────────────────────────
// Rarity scales with required level:
//   Nv.1-9: common    Nv.10-19: uncommon
//   Nv.20-29: rare    Nv.30-39: epic    Nv.40+: legendary

export const RECIPES: CraftingRecipe[] = [
  // ════════════════════════════════════════════════════════════════
  // ── Herbalism — potions & elixirs ──────────────────────────────
  // ════════════════════════════════════════════════════════════════
  { id: 'potion_soin', name: 'Potion de Soin', profession: 'herbalism', requiredLevel: 1,
    materials: [{ materialID: 'herbe_soins', amount: 3 }],
    result: { type: 'potion', itemID: 'potion_soin', amount: 1 } },
  { id: 'potion_endurance', name: 'Potion d\'Endurance', profession: 'herbalism', requiredLevel: 3,
    materials: [{ materialID: 'herbe_soins', amount: 4 }],
    result: { type: 'potion', itemID: 'potion_endurance', amount: 1 } },
  { id: 'potion_investiture', name: 'Potion d\'Investiture', profession: 'herbalism', requiredLevel: 5,
    materials: [{ materialID: 'herbe_soins', amount: 2 }, { materialID: 'racine_orage', amount: 1 }],
    result: { type: 'potion', itemID: 'potion_investiture', amount: 1 } },
  { id: 'potion_antidote', name: 'Antidote', profession: 'herbalism', requiredLevel: 7,
    materials: [{ materialID: 'herbe_soins', amount: 3 }, { materialID: 'fleur_nalthis', amount: 1 }],
    result: { type: 'potion', itemID: 'potion_antidote', amount: 1 } },
  { id: 'potion_soin_ii', name: 'Grande Potion de Soin', profession: 'herbalism', requiredLevel: 10,
    materials: [{ materialID: 'herbe_soins', amount: 5 }, { materialID: 'racine_orage', amount: 1 }],
    result: { type: 'potion', itemID: 'potion_soin_ii', amount: 1 } },
  { id: 'potion_vitesse', name: 'Potion de Vitesse', profession: 'herbalism', requiredLevel: 12,
    materials: [{ materialID: 'racine_orage', amount: 2 }, { materialID: 'herbe_soins', amount: 2 }],
    result: { type: 'potion', itemID: 'potion_vitesse', amount: 1 } },
  { id: 'elixir_vitalite', name: 'Élixir de Vitalité', profession: 'herbalism', requiredLevel: 15,
    materials: [{ materialID: 'fleur_nalthis', amount: 2 }, { materialID: 'herbe_soins', amount: 3 }],
    result: { type: 'potion', itemID: 'elixir_vitalite', amount: 1 } },
  { id: 'potion_bouclier', name: 'Potion de Bouclier', profession: 'herbalism', requiredLevel: 18,
    materials: [{ materialID: 'racine_orage', amount: 2 }, { materialID: 'fleur_nalthis', amount: 1 }],
    result: { type: 'potion', itemID: 'potion_bouclier', amount: 1 } },
  { id: 'potion_investiture_ii', name: 'Grande Potion d\'Investiture', profession: 'herbalism', requiredLevel: 20,
    materials: [{ materialID: 'racine_orage', amount: 3 }, { materialID: 'fleur_nalthis', amount: 1 }],
    result: { type: 'potion', itemID: 'potion_investiture_ii', amount: 1 } },
  { id: 'potion_force', name: 'Potion de Force', profession: 'herbalism', requiredLevel: 22,
    materials: [{ materialID: 'fleur_nalthis', amount: 2 }, { materialID: 'racine_orage', amount: 2 }],
    result: { type: 'potion', itemID: 'potion_force', amount: 1 } },
  { id: 'elixir_orage', name: 'Élixir d\'Orage', profession: 'herbalism', requiredLevel: 25,
    materials: [{ materialID: 'racine_orage', amount: 3 }, { materialID: 'mousse_shadesmar', amount: 1 }],
    result: { type: 'potion', itemID: 'elixir_orage', amount: 1 } },
  { id: 'potion_regeneration', name: 'Potion de Régénération', profession: 'herbalism', requiredLevel: 28,
    materials: [{ materialID: 'mousse_shadesmar', amount: 1 }, { materialID: 'fleur_nalthis', amount: 2 }],
    result: { type: 'potion', itemID: 'potion_regeneration', amount: 1 } },
  { id: 'elixir_cosmos', name: 'Élixir Cosmique', profession: 'herbalism', requiredLevel: 30,
    materials: [{ materialID: 'mousse_shadesmar', amount: 2 }, { materialID: 'fleur_nalthis', amount: 2 }],
    result: { type: 'potion', itemID: 'elixir_cosmos', amount: 1 } },
  { id: 'potion_soin_iii', name: 'Potion de Soin Majeure', profession: 'herbalism', requiredLevel: 35,
    materials: [{ materialID: 'lotus_investiture', amount: 1 }, { materialID: 'herbe_soins', amount: 5 }],
    result: { type: 'potion', itemID: 'potion_soin_iii', amount: 1 } },
  { id: 'elixir_supreme', name: 'Élixir Suprême', profession: 'herbalism', requiredLevel: 40,
    materials: [{ materialID: 'lotus_investiture', amount: 1 }, { materialID: 'fleur_nalthis', amount: 2 }, { materialID: 'mousse_shadesmar', amount: 2 }],
    result: { type: 'potion', itemID: 'elixir_supreme', amount: 1 } },
  { id: 'potion_immortalite', name: 'Potion d\'Immortalité', profession: 'herbalism', requiredLevel: 45,
    materials: [{ materialID: 'lotus_investiture', amount: 2 }, { materialID: 'racine_orage', amount: 3 }],
    result: { type: 'potion', itemID: 'potion_immortalite', amount: 1 } },
  { id: 'elixir_divin', name: 'Élixir Divin', profession: 'herbalism', requiredLevel: 50,
    materials: [{ materialID: 'lotus_investiture', amount: 2 }, { materialID: 'mousse_shadesmar', amount: 3 }],
    result: { type: 'potion', itemID: 'elixir_divin', amount: 1 } },

  // ════════════════════════════════════════════════════════════════
  // ── Mining — weapons, helmets, armor ───────────────────────────
  // ════════════════════════════════════════════════════════════════
  { id: 'lingot_acier', name: 'Lingot d\'Acier', profession: 'mining', requiredLevel: 1,
    materials: [{ materialID: 'minerai_fer', amount: 4 }],
    result: { type: 'equipment', itemID: 'lingot_acier', amount: 1 } },
  { id: 'couteau_fer', name: 'Couteau de Fer', profession: 'mining', requiredLevel: 3,
    materials: [{ materialID: 'minerai_fer', amount: 5 }],
    result: { type: 'equipment', itemID: 'couteau_fer', amount: 1 } },
  { id: 'dague_fer', name: 'Dague de Fer', profession: 'mining', requiredLevel: 5,
    materials: [{ materialID: 'minerai_fer', amount: 3 }, { materialID: 'minerai_acier', amount: 1 }],
    result: { type: 'equipment', itemID: 'dague_fer', amount: 1 } },
  { id: 'casque_fer', name: 'Casque de Fer', profession: 'mining', requiredLevel: 7,
    materials: [{ materialID: 'minerai_fer', amount: 5 }, { materialID: 'minerai_acier', amount: 1 }],
    result: { type: 'equipment', itemID: 'casque_fer', amount: 1 } },
  { id: 'lame_pewter', name: 'Lame de Pewter', profession: 'mining', requiredLevel: 10,
    materials: [{ materialID: 'minerai_pewter', amount: 3 }, { materialID: 'minerai_fer', amount: 2 }],
    result: { type: 'equipment', itemID: 'lame_pewter', amount: 1 } },
  { id: 'plastron_fer', name: 'Plastron de Fer', profession: 'mining', requiredLevel: 12,
    materials: [{ materialID: 'minerai_fer', amount: 6 }, { materialID: 'minerai_acier', amount: 2 }],
    result: { type: 'equipment', itemID: 'plastron_fer', amount: 1 } },
  { id: 'casque_acier', name: 'Casque d\'Acier', profession: 'mining', requiredLevel: 15,
    materials: [{ materialID: 'minerai_acier', amount: 4 }, { materialID: 'minerai_fer', amount: 2 }],
    result: { type: 'equipment', itemID: 'casque_acier', amount: 1 } },
  { id: 'epaulieres_acier', name: 'Épaulières d\'Acier', profession: 'mining', requiredLevel: 18,
    materials: [{ materialID: 'minerai_acier', amount: 5 }, { materialID: 'minerai_pewter', amount: 1 }],
    result: { type: 'equipment', itemID: 'epaulieres_acier', amount: 1 } },
  { id: 'epee_acier', name: 'Épée d\'Acier Renforcé', profession: 'mining', requiredLevel: 20,
    materials: [{ materialID: 'minerai_acier', amount: 5 }, { materialID: 'minerai_pewter', amount: 2 }],
    result: { type: 'equipment', itemID: 'epee_acier', amount: 1 } },
  { id: 'jambieres_acier', name: 'Jambières d\'Acier', profession: 'mining', requiredLevel: 22,
    materials: [{ materialID: 'minerai_acier', amount: 4 }, { materialID: 'minerai_pewter', amount: 2 }],
    result: { type: 'equipment', itemID: 'jambieres_acier', amount: 1 } },
  { id: 'bouclier_gemme', name: 'Bouclier de Gemme', profession: 'mining', requiredLevel: 25,
    materials: [{ materialID: 'gemme_lumiere', amount: 2 }, { materialID: 'minerai_acier', amount: 3 }],
    result: { type: 'equipment', itemID: 'bouclier_gemme', amount: 1 } },
  { id: 'ceinture_acier', name: 'Ceinture d\'Acier Renforcé', profession: 'mining', requiredLevel: 28,
    materials: [{ materialID: 'minerai_acier', amount: 4 }, { materialID: 'gemme_lumiere', amount: 1 }],
    result: { type: 'equipment', itemID: 'ceinture_acier', amount: 1 } },
  { id: 'plastron_acier', name: 'Plastron d\'Acier Supérieur', profession: 'mining', requiredLevel: 30,
    materials: [{ materialID: 'minerai_acier', amount: 6 }, { materialID: 'gemme_lumiere', amount: 1 }],
    result: { type: 'equipment', itemID: 'plastron_acier', amount: 1 } },
  { id: 'bottes_gemme', name: 'Bottes de Gemcœur', profession: 'mining', requiredLevel: 33,
    materials: [{ materialID: 'gemme_lumiere', amount: 2 }, { materialID: 'minerai_pewter', amount: 2 }],
    result: { type: 'equipment', itemID: 'bottes_gemme', amount: 1 } },
  { id: 'casque_gemme', name: 'Casque de Gemcœur', profession: 'mining', requiredLevel: 36,
    materials: [{ materialID: 'gemme_lumiere', amount: 2 }, { materialID: 'minerai_acier', amount: 4 }],
    result: { type: 'equipment', itemID: 'casque_gemme', amount: 1 } },
  { id: 'lame_gemme', name: 'Lame de Gemcœur', profession: 'mining', requiredLevel: 40,
    materials: [{ materialID: 'gemme_lumiere', amount: 3 }, { materialID: 'minerai_pewter', amount: 3 }],
    result: { type: 'equipment', itemID: 'lame_gemme', amount: 1 } },
  { id: 'anneau_atium', name: 'Anneau d\'Atium', profession: 'mining', requiredLevel: 45,
    materials: [{ materialID: 'minerai_atium', amount: 2 }, { materialID: 'gemme_lumiere', amount: 1 }],
    result: { type: 'equipment', itemID: 'anneau_atium', amount: 1 } },
  { id: 'arme_atium', name: 'Arme d\'Atium', profession: 'mining', requiredLevel: 50,
    materials: [{ materialID: 'minerai_atium', amount: 3 }, { materialID: 'minerai_acier', amount: 5 }],
    result: { type: 'equipment', itemID: 'arme_atium', amount: 1 } },

  // ════════════════════════════════════════════════════════════════
  // ── Woodcutting — bows, staves, shields, weapons ───────────────
  // ════════════════════════════════════════════════════════════════
  { id: 'arc_simple', name: 'Arc Simple', profession: 'woodcutting', requiredLevel: 1,
    materials: [{ materialID: 'bois_commun', amount: 5 }],
    result: { type: 'equipment', itemID: 'arc_simple', amount: 1 } },
  { id: 'baton_commun', name: 'Bâton de Voyageur', profession: 'woodcutting', requiredLevel: 4,
    materials: [{ materialID: 'bois_commun', amount: 4 }],
    result: { type: 'equipment', itemID: 'baton_commun', amount: 1 } },
  { id: 'bouclier_bois', name: 'Bouclier en Bois', profession: 'woodcutting', requiredLevel: 8,
    materials: [{ materialID: 'bois_commun', amount: 6 }],
    result: { type: 'equipment', itemID: 'bouclier_bois', amount: 1 } },
  { id: 'arc_renforce', name: 'Arc Renforcé', profession: 'woodcutting', requiredLevel: 12,
    materials: [{ materialID: 'bois_commun', amount: 5 }, { materialID: 'bois_roshar', amount: 1 }],
    result: { type: 'equipment', itemID: 'arc_renforce', amount: 1 } },
  { id: 'baton_coquebois', name: 'Bâton de Coquebois', profession: 'woodcutting', requiredLevel: 15,
    materials: [{ materialID: 'bois_roshar', amount: 3 }, { materialID: 'bois_commun', amount: 2 }],
    result: { type: 'equipment', itemID: 'baton_coquebois', amount: 1 } },
  { id: 'lance_bois', name: 'Lance de Bois Renforcé', profession: 'woodcutting', requiredLevel: 18,
    materials: [{ materialID: 'bois_roshar', amount: 4 }],
    result: { type: 'equipment', itemID: 'lance_bois', amount: 1 } },
  { id: 'arc_roshar', name: 'Arc de Coquebois', profession: 'woodcutting', requiredLevel: 22,
    materials: [{ materialID: 'bois_roshar', amount: 5 }],
    result: { type: 'equipment', itemID: 'arc_roshar', amount: 1 } },
  { id: 'bouclier_coquebois', name: 'Bouclier de Coquebois', profession: 'woodcutting', requiredLevel: 25,
    materials: [{ materialID: 'bois_roshar', amount: 4 }, { materialID: 'bois_commun', amount: 3 }],
    result: { type: 'equipment', itemID: 'bouclier_coquebois', amount: 1 } },
  { id: 'lance_petrifie', name: 'Lance Pétrifiée', profession: 'woodcutting', requiredLevel: 30,
    materials: [{ materialID: 'bois_petrifie', amount: 3 }, { materialID: 'bois_roshar', amount: 2 }],
    result: { type: 'equipment', itemID: 'lance_petrifie', amount: 1 } },
  { id: 'arc_petrifie', name: 'Arc Pétrifié', profession: 'woodcutting', requiredLevel: 35,
    materials: [{ materialID: 'bois_petrifie', amount: 4 }, { materialID: 'bois_commun', amount: 2 }],
    result: { type: 'equipment', itemID: 'arc_petrifie', amount: 1 } },
  { id: 'baton_ancien', name: 'Bâton Ancien', profession: 'woodcutting', requiredLevel: 40,
    materials: [{ materialID: 'bois_petrifie', amount: 4 }, { materialID: 'bois_roshar', amount: 3 }],
    result: { type: 'equipment', itemID: 'baton_ancien', amount: 1 } },
  { id: 'arc_legendaire', name: 'Arc du Cosmérique', profession: 'woodcutting', requiredLevel: 50,
    materials: [{ materialID: 'bois_petrifie', amount: 5 }, { materialID: 'bois_roshar', amount: 4 }],
    result: { type: 'equipment', itemID: 'arc_legendaire', amount: 1 } },

  // ════════════════════════════════════════════════════════════════
  // ── Skinning — armor, capes, boots, gloves ─────────────────────
  // ════════════════════════════════════════════════════════════════
  { id: 'armure_cuir', name: 'Armure de Cuir', profession: 'skinning', requiredLevel: 1,
    materials: [{ materialID: 'cuir_brut', amount: 5 }],
    result: { type: 'equipment', itemID: 'armure_cuir', amount: 1 } },
  { id: 'gants_cuir', name: 'Gants de Cuir', profession: 'skinning', requiredLevel: 4,
    materials: [{ materialID: 'cuir_brut', amount: 3 }],
    result: { type: 'equipment', itemID: 'gants_cuir', amount: 1 } },
  { id: 'ceinture_cuir', name: 'Ceinture de Cuir', profession: 'skinning', requiredLevel: 6,
    materials: [{ materialID: 'cuir_brut', amount: 3 }],
    result: { type: 'equipment', itemID: 'ceinture_cuir', amount: 1 } },
  { id: 'bottes_cuir', name: 'Bottes de Cuir', profession: 'skinning', requiredLevel: 8,
    materials: [{ materialID: 'cuir_brut', amount: 4 }],
    result: { type: 'equipment', itemID: 'bottes_cuir', amount: 1 } },
  { id: 'cape_cuir', name: 'Cape de Cuir', profession: 'skinning', requiredLevel: 10,
    materials: [{ materialID: 'cuir_brut', amount: 5 }],
    result: { type: 'equipment', itemID: 'cape_cuir', amount: 1 } },
  { id: 'epaulieres_cuir', name: 'Épaulières de Cuir', profession: 'skinning', requiredLevel: 12,
    materials: [{ materialID: 'cuir_brut', amount: 4 }, { materialID: 'ecailles_crustace', amount: 1 }],
    result: { type: 'equipment', itemID: 'epaulieres_cuir', amount: 1 } },
  { id: 'gantelets_cuir', name: 'Gantelets de Cuir Renforcé', profession: 'skinning', requiredLevel: 15,
    materials: [{ materialID: 'cuir_brut', amount: 3 }, { materialID: 'ecailles_crustace', amount: 1 }],
    result: { type: 'equipment', itemID: 'gantelets_cuir', amount: 1 } },
  { id: 'jambieres_cuir', name: 'Jambières de Cuir Renforcé', profession: 'skinning', requiredLevel: 18,
    materials: [{ materialID: 'cuir_brut', amount: 4 }, { materialID: 'ecailles_crustace', amount: 2 }],
    result: { type: 'equipment', itemID: 'jambieres_cuir', amount: 1 } },
  { id: 'plastron_crustace', name: 'Plastron de Crustacé', profession: 'skinning', requiredLevel: 20,
    materials: [{ materialID: 'ecailles_crustace', amount: 3 }, { materialID: 'cuir_brut', amount: 2 }],
    result: { type: 'equipment', itemID: 'plastron_crustace', amount: 1 } },
  { id: 'bottes_ecailles', name: 'Bottes d\'Écailles', profession: 'skinning', requiredLevel: 23,
    materials: [{ materialID: 'ecailles_crustace', amount: 3 }],
    result: { type: 'equipment', itemID: 'bottes_ecailles', amount: 1 } },
  { id: 'cape_ecailles', name: 'Cape d\'Écailles', profession: 'skinning', requiredLevel: 25,
    materials: [{ materialID: 'ecailles_crustace', amount: 4 }],
    result: { type: 'equipment', itemID: 'cape_ecailles', amount: 1 } },
  { id: 'jambiere_ecailles', name: 'Jambières d\'Écailles', profession: 'skinning', requiredLevel: 28,
    materials: [{ materialID: 'ecailles_crustace', amount: 4 }, { materialID: 'cuir_brut', amount: 2 }],
    result: { type: 'equipment', itemID: 'jambiere_ecailles', amount: 1 } },
  { id: 'epaulieres_larkin', name: 'Épaulières de Larkin', profession: 'skinning', requiredLevel: 30,
    materials: [{ materialID: 'peau_larkin', amount: 2 }, { materialID: 'ecailles_crustace', amount: 1 }],
    result: { type: 'equipment', itemID: 'epaulieres_larkin', amount: 1 } },
  { id: 'gants_larkin', name: 'Gants de Larkin', profession: 'skinning', requiredLevel: 33,
    materials: [{ materialID: 'peau_larkin', amount: 2 }, { materialID: 'cuir_brut', amount: 2 }],
    result: { type: 'equipment', itemID: 'gants_larkin', amount: 1 } },
  { id: 'cape_larkin', name: 'Cape de Larkin', profession: 'skinning', requiredLevel: 35,
    materials: [{ materialID: 'peau_larkin', amount: 2 }, { materialID: 'ecailles_crustace', amount: 2 }],
    result: { type: 'equipment', itemID: 'cape_larkin', amount: 1 } },
  { id: 'plastron_larkin', name: 'Plastron de Larkin', profession: 'skinning', requiredLevel: 38,
    materials: [{ materialID: 'peau_larkin', amount: 3 }, { materialID: 'ecailles_crustace', amount: 2 }],
    result: { type: 'equipment', itemID: 'plastron_larkin', amount: 1 } },
  { id: 'bottes_epine', name: 'Bottes d\'Épine', profession: 'skinning', requiredLevel: 40,
    materials: [{ materialID: 'carapace_epine', amount: 2 }, { materialID: 'peau_larkin', amount: 1 }],
    result: { type: 'equipment', itemID: 'bottes_epine', amount: 1 } },
  { id: 'armure_epine', name: 'Armure d\'Épine', profession: 'skinning', requiredLevel: 45,
    materials: [{ materialID: 'carapace_epine', amount: 3 }, { materialID: 'peau_larkin', amount: 2 }],
    result: { type: 'equipment', itemID: 'armure_epine', amount: 1 } },
  { id: 'armure_legendaire', name: 'Armure du Cosmere', profession: 'skinning', requiredLevel: 50,
    materials: [{ materialID: 'carapace_epine', amount: 4 }, { materialID: 'peau_larkin', amount: 3 }],
    result: { type: 'equipment', itemID: 'armure_legendaire', amount: 1 } },

  // ════════════════════════════════════════════════════════════════
  // ── Enchanting — enchantments & scrolls ────────────────────────
  // ════════════════════════════════════════════════════════════════
  { id: 'enchant_protection', name: 'Enchantement de Protection', profession: 'enchanting', requiredLevel: 1,
    materials: [{ materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'enchantment', itemID: 'enchant_protection', amount: 1 } },
  { id: 'enchant_vigueur', name: 'Enchantement de Vigueur', profession: 'enchanting', requiredLevel: 3,
    materials: [{ materialID: 'poudre_arcane', amount: 4 }],
    result: { type: 'enchantment', itemID: 'enchant_vigueur', amount: 1 } },
  { id: 'enchant_force', name: 'Enchantement de Force', profession: 'enchanting', requiredLevel: 5,
    materials: [{ materialID: 'poudre_arcane', amount: 4 }],
    result: { type: 'enchantment', itemID: 'enchant_force', amount: 1 } },
  { id: 'enchant_chance', name: 'Enchantement de Chance', profession: 'enchanting', requiredLevel: 8,
    materials: [{ materialID: 'poudre_arcane', amount: 5 }],
    result: { type: 'enchantment', itemID: 'enchant_chance', amount: 1 } },
  { id: 'enchant_agilite', name: 'Enchantement d\'Agilité', profession: 'enchanting', requiredLevel: 10,
    materials: [{ materialID: 'poudre_arcane', amount: 5 }, { materialID: 'sable_blanc', amount: 1 }],
    result: { type: 'enchantment', itemID: 'enchant_agilite', amount: 1 } },
  { id: 'enchant_vitesse', name: 'Enchantement de Vitesse', profession: 'enchanting', requiredLevel: 13,
    materials: [{ materialID: 'sable_blanc', amount: 2 }, { materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'enchantment', itemID: 'enchant_vitesse', amount: 1 } },
  { id: 'enchant_esprit', name: 'Enchantement d\'Esprit', profession: 'enchanting', requiredLevel: 15,
    materials: [{ materialID: 'poudre_arcane', amount: 4 }, { materialID: 'cristal_investiture', amount: 1 }],
    result: { type: 'enchantment', itemID: 'enchant_esprit', amount: 1 } },
  { id: 'enchant_absorption', name: 'Enchantement d\'Absorption', profession: 'enchanting', requiredLevel: 18,
    materials: [{ materialID: 'cristal_investiture', amount: 1 }, { materialID: 'poudre_arcane', amount: 5 }],
    result: { type: 'enchantment', itemID: 'enchant_absorption', amount: 1 } },
  { id: 'enchant_investiture', name: 'Enchantement d\'Investiture', profession: 'enchanting', requiredLevel: 20,
    materials: [{ materialID: 'cristal_investiture', amount: 2 }, { materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'enchantment', itemID: 'enchant_investiture', amount: 1 } },
  { id: 'enchant_resistance', name: 'Enchantement de Résistance', profession: 'enchanting', requiredLevel: 23,
    materials: [{ materialID: 'cristal_investiture', amount: 2 }, { materialID: 'sable_blanc', amount: 1 }],
    result: { type: 'enchantment', itemID: 'enchant_resistance', amount: 1 } },
  { id: 'enchant_devastation', name: 'Enchantement de Dévastation', profession: 'enchanting', requiredLevel: 25,
    materials: [{ materialID: 'cristal_investiture', amount: 2 }, { materialID: 'sable_blanc', amount: 2 }],
    result: { type: 'enchantment', itemID: 'enchant_devastation', amount: 1 } },
  { id: 'enchant_cosmos', name: 'Enchantement Cosmérique', profession: 'enchanting', requiredLevel: 30,
    materials: [{ materialID: 'cristal_investiture', amount: 2 }, { materialID: 'sable_blanc', amount: 3 }],
    result: { type: 'enchantment', itemID: 'enchant_cosmos', amount: 1 } },
  { id: 'enchant_parfait', name: 'Enchantement Parfait', profession: 'enchanting', requiredLevel: 35,
    materials: [{ materialID: 'cristal_investiture', amount: 3 }, { materialID: 'sable_blanc', amount: 2 }, { materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'enchantment', itemID: 'enchant_parfait', amount: 1 } },
  { id: 'enchant_legendaire', name: 'Enchantement Légendaire', profession: 'enchanting', requiredLevel: 40,
    materials: [{ materialID: 'cristal_investiture', amount: 3 }, { materialID: 'sable_blanc', amount: 3 }, { materialID: 'poudre_arcane', amount: 5 }],
    result: { type: 'enchantment', itemID: 'enchant_legendaire', amount: 1 } },
  { id: 'enchant_supreme', name: 'Enchantement Suprême', profession: 'enchanting', requiredLevel: 45,
    materials: [{ materialID: 'cristal_investiture', amount: 4 }, { materialID: 'sable_blanc', amount: 4 }],
    result: { type: 'enchantment', itemID: 'enchant_supreme', amount: 1 } },
  { id: 'enchant_divin', name: 'Enchantement Divin', profession: 'enchanting', requiredLevel: 50,
    materials: [{ materialID: 'cristal_investiture', amount: 5 }, { materialID: 'sable_blanc', amount: 5 }],
    result: { type: 'enchantment', itemID: 'enchant_divin', amount: 1 } },

  // ── Nv.60+ : Herbalism ──────────────────────────────────────
  { id: 'potion_phoenix', name: 'Potion du Phénix', profession: 'herbalism', requiredLevel: 60,
    materials: [{ materialID: 'racine_ancienne', amount: 5 }, { materialID: 'cristal_investiture', amount: 3 }],
    result: { type: 'consumable', itemID: 'potion_phoenix', amount: 1 } },
  { id: 'elixir_cosmere', name: 'Élixir Cosmérique', profession: 'herbalism', requiredLevel: 70,
    materials: [{ materialID: 'racine_ancienne', amount: 8 }, { materialID: 'cristal_investiture', amount: 5 }, { materialID: 'sable_blanc', amount: 3 }],
    result: { type: 'consumable', itemID: 'elixir_cosmere', amount: 1 } },
  { id: 'potion_transcendance', name: 'Potion de Transcendance', profession: 'herbalism', requiredLevel: 80,
    materials: [{ materialID: 'racine_ancienne', amount: 10 }, { materialID: 'cristal_investiture', amount: 8 }, { materialID: 'sable_blanc', amount: 5 }],
    result: { type: 'consumable', itemID: 'potion_transcendance', amount: 1 } },
  { id: 'elixir_eternite', name: 'Élixir d\'Éternité', profession: 'herbalism', requiredLevel: 90,
    materials: [{ materialID: 'racine_ancienne', amount: 12 }, { materialID: 'cristal_investiture', amount: 10 }, { materialID: 'sable_blanc', amount: 8 }],
    result: { type: 'consumable', itemID: 'elixir_eternite', amount: 1 } },
  { id: 'elixir_adonalsium', name: 'Élixir d\'Adonalsium', profession: 'herbalism', requiredLevel: 100,
    materials: [{ materialID: 'racine_ancienne', amount: 15 }, { materialID: 'cristal_investiture', amount: 12 }, { materialID: 'sable_blanc', amount: 10 }],
    result: { type: 'consumable', itemID: 'elixir_adonalsium', amount: 1 } },

  // ── Nv.60+ : Mining ─────────────────────────────────────────
  { id: 'epee_cosmere', name: 'Épée Cosmérique', profession: 'mining', requiredLevel: 60,
    materials: [{ materialID: 'minerai_etain', amount: 6 }, { materialID: 'cristal_investiture', amount: 4 }, { materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'equipment', itemID: 'epee_cosmere', amount: 1 } },
  { id: 'bouclier_shard', name: 'Bouclier de Shard', profession: 'mining', requiredLevel: 70,
    materials: [{ materialID: 'minerai_etain', amount: 8 }, { materialID: 'cristal_investiture', amount: 5 }, { materialID: 'sable_blanc', amount: 3 }],
    result: { type: 'equipment', itemID: 'bouclier_shard', amount: 1 } },
  { id: 'casque_cosmere', name: 'Casque du Cosmere', profession: 'mining', requiredLevel: 80,
    materials: [{ materialID: 'minerai_etain', amount: 10 }, { materialID: 'cristal_investiture', amount: 8 }],
    result: { type: 'equipment', itemID: 'casque_cosmere', amount: 1 } },
  { id: 'armure_investiture', name: 'Armure d\'Investiture', profession: 'mining', requiredLevel: 90,
    materials: [{ materialID: 'minerai_etain', amount: 12 }, { materialID: 'cristal_investiture', amount: 10 }, { materialID: 'sable_blanc', amount: 6 }],
    result: { type: 'equipment', itemID: 'armure_investiture', amount: 1 } },
  { id: 'lame_adonalsium', name: 'Lame d\'Adonalsium', profession: 'mining', requiredLevel: 100,
    materials: [{ materialID: 'minerai_etain', amount: 15 }, { materialID: 'cristal_investiture', amount: 12 }, { materialID: 'sable_blanc', amount: 10 }],
    result: { type: 'equipment', itemID: 'lame_adonalsium', amount: 1 } },

  // ── Nv.60+ : Woodcutting ────────────────────────────────────
  { id: 'arc_cosmere', name: 'Arc du Cosmere', profession: 'woodcutting', requiredLevel: 60,
    materials: [{ materialID: 'bois_dur', amount: 6 }, { materialID: 'cristal_investiture', amount: 3 }],
    result: { type: 'equipment', itemID: 'arc_cosmere', amount: 1 } },
  { id: 'baton_shard', name: 'Bâton de Shard', profession: 'woodcutting', requiredLevel: 70,
    materials: [{ materialID: 'bois_dur', amount: 8 }, { materialID: 'cristal_investiture', amount: 5 }, { materialID: 'poudre_arcane', amount: 3 }],
    result: { type: 'equipment', itemID: 'baton_shard', amount: 1 } },
  { id: 'bouclier_ancien', name: 'Bouclier des Anciens', profession: 'woodcutting', requiredLevel: 80,
    materials: [{ materialID: 'bois_dur', amount: 10 }, { materialID: 'cristal_investiture', amount: 6 }],
    result: { type: 'equipment', itemID: 'bouclier_ancien', amount: 1 } },
  { id: 'arc_adonalsium', name: 'Arc d\'Adonalsium', profession: 'woodcutting', requiredLevel: 100,
    materials: [{ materialID: 'bois_dur', amount: 15 }, { materialID: 'cristal_investiture', amount: 12 }, { materialID: 'sable_blanc', amount: 8 }],
    result: { type: 'equipment', itemID: 'arc_adonalsium', amount: 1 } },

  // ── Nv.60+ : Skinning ──────────────────────────────────────
  { id: 'cape_cosmere', name: 'Cape Cosmérique', profession: 'skinning', requiredLevel: 60,
    materials: [{ materialID: 'cuir_souple', amount: 6 }, { materialID: 'cristal_investiture', amount: 3 }],
    result: { type: 'equipment', itemID: 'cape_cosmere', amount: 1 } },
  { id: 'bottes_cosmere', name: 'Bottes Cosmériques', profession: 'skinning', requiredLevel: 70,
    materials: [{ materialID: 'cuir_souple', amount: 8 }, { materialID: 'cristal_investiture', amount: 5 }],
    result: { type: 'equipment', itemID: 'bottes_cosmere', amount: 1 } },
  { id: 'ceinture_cosmere', name: 'Ceinture Cosmérique', profession: 'skinning', requiredLevel: 80,
    materials: [{ materialID: 'cuir_souple', amount: 10 }, { materialID: 'cristal_investiture', amount: 6 }, { materialID: 'poudre_arcane', amount: 4 }],
    result: { type: 'equipment', itemID: 'ceinture_cosmere', amount: 1 } },
  { id: 'armure_cosmere', name: 'Armure du Cosmere', profession: 'skinning', requiredLevel: 90,
    materials: [{ materialID: 'cuir_souple', amount: 12 }, { materialID: 'cristal_investiture', amount: 10 }],
    result: { type: 'equipment', itemID: 'armure_cosmere', amount: 1 } },
  { id: 'tenue_adonalsium', name: 'Tenue d\'Adonalsium', profession: 'skinning', requiredLevel: 100,
    materials: [{ materialID: 'cuir_souple', amount: 15 }, { materialID: 'cristal_investiture', amount: 12 }, { materialID: 'sable_blanc', amount: 10 }],
    result: { type: 'equipment', itemID: 'tenue_adonalsium', amount: 1 } },

  // ── Nv.60+ : Enchanting ─────────────────────────────────────
  { id: 'enchant_cosmere', name: 'Enchantement Cosmérique', profession: 'enchanting', requiredLevel: 60,
    materials: [{ materialID: 'cristal_investiture', amount: 6 }, { materialID: 'sable_blanc', amount: 5 }, { materialID: 'poudre_arcane', amount: 4 }],
    result: { type: 'enchantment', itemID: 'enchant_cosmere', amount: 1 } },
  { id: 'enchant_shard', name: 'Enchantement de Shard', profession: 'enchanting', requiredLevel: 70,
    materials: [{ materialID: 'cristal_investiture', amount: 8 }, { materialID: 'sable_blanc', amount: 6 }],
    result: { type: 'enchantment', itemID: 'enchant_shard', amount: 1 } },
  { id: 'enchant_cosmique', name: 'Enchantement Cosmique', profession: 'enchanting', requiredLevel: 80,
    materials: [{ materialID: 'cristal_investiture', amount: 10 }, { materialID: 'sable_blanc', amount: 8 }],
    result: { type: 'enchantment', itemID: 'enchant_cosmique', amount: 1 } },
  { id: 'enchant_eternel', name: 'Enchantement Éternel', profession: 'enchanting', requiredLevel: 90,
    materials: [{ materialID: 'cristal_investiture', amount: 12 }, { materialID: 'sable_blanc', amount: 10 }],
    result: { type: 'enchantment', itemID: 'enchant_eternel', amount: 1 } },
  { id: 'enchant_adonalsium', name: 'Enchantement d\'Adonalsium', profession: 'enchanting', requiredLevel: 100,
    materials: [{ materialID: 'cristal_investiture', amount: 15 }, { materialID: 'sable_blanc', amount: 12 }, { materialID: 'poudre_arcane', amount: 10 }],
    result: { type: 'enchantment', itemID: 'enchant_adonalsium', amount: 1 } },
];
